"""add_color_and_icon_to_accounts

Revision ID: eed3782eb47d
Revises: 1d87292e4fd4
Create Date: 2026-04-10 13:49:22.900294

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eed3782eb47d"
down_revision: Union[str, Sequence[str], None] = "1d87292e4fd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("color", sa.String(length=7), nullable=True))
    op.add_column("accounts", sa.Column("icon", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "icon")
    op.drop_column("accounts", "color")
    # ### end Alembic commands ###
